name: Build Clem.exe Release

on:
  workflow_run:
    workflows: [Build Clem.exe]
    branches: [main]
    # tags: ['v*']
    types: 
      - completed

jobs:
  release:
    #if: ${{ startsWith(github.event.ref, 'refs/tags') && github.event.workflow_run.conclusion == 'success' }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build release of Clem.exe
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Download artifact
      uses: actions/download-artifact@v7
      with:
        path: Clem_exe
